# docker-compose.yml

version: '3.9'
services:
  consul:
    image: consul:1.14
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
 
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    ports:
      - "50051:50051"
    depends_on:
      - user-db
      - consul
  
  user-db:
    image: postgres:latest
    env_file:
      - ./user-service/.env
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  invoice-service:
    build:
      context: ./invoice-service
      dockerfile: Dockerfile
    env_file:
      - ./invoice-service/.env
    ports:
      - "50052:50052"
    depends_on:
      - invoice-db
      - consul

  invoice-db:
    image: postgres:latest
    env_file:
      - ./invoice-service/.env
    ports:
      - "5434:5432"
    volumes:
      - invoice-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  invoice-db-data:

