# docker-compose.yml

version: '3.9'
services:
  consul:
    image: consul:1.14
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  # invoiceservice:
  #   build: ./invoiceservice
  #   environment:
  #     - DB_URL=postgres://${INVOICE_DB_USER}:${INVOICE_DB_PASSWORD}@${INVOICE_DB_HOST}:${INVOICE_DB_PORT}/${INVOICE_DB_NAME}?sslmode=disable
  #   depends_on:
  #     - invoice-db
  #     - consul
  #   volumes:
  #     - ./invoiceservice/migrations:/migrations
  #   ports:
  #     - "8080:8080"

  # invoice-db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: ${INVOICE_DB_USER}
  #     POSTGRES_PASSWORD: ${INVOICE_DB_PASSWORD}
  #     POSTGRES_DB: ${INVOICE_DB_NAME}
  #   ports:
  #     - "${INVOICE_DB_PORT}:5433"
  
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    ports:
      - "50051:50051"
    depends_on:
      - user-db
      - consul
  
  user-db:
    image: postgres:latest
    env_file:
      - ./user-service/.env
    volumes:
      - user-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:

