# docker-compose.yml

version: '3.9'
services:
  invoiceservice:
    build: ./invoiceservice
    environment:
      - DB_URL=postgres://${INVOICE_DB_USER}:${INVOICE_DB_PASSWORD}@${INVOICE_DB_HOST}:${INVOICE_DB_PORT}/${INVOICE_DB_NAME}?sslmode=disable
    depends_on:
      - invoice-db
    volumes:
      - ./invoiceservice/migrations:/migrations
    ports:
      - "8081:8080"

  invoice-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${INVOICE_DB_USER}
      POSTGRES_PASSWORD: ${INVOICE_DB_PASSWORD}
      POSTGRES_DB: ${INVOICE_DB_NAME}
    ports:
      - "${INVOICE_DB_PORT}:5432"
    


