// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: reminders-service/proto/reminders.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId     string `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	DueDate       string `protobuf:"bytes,2,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CustomerEmail string `protobuf:"bytes,3,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
}

func (x *ScheduleReminderRequest) Reset() {
	*x = ScheduleReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminders_service_proto_reminders_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleReminderRequest) ProtoMessage() {}

func (x *ScheduleReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminders_service_proto_reminders_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleReminderRequest.ProtoReflect.Descriptor instead.
func (*ScheduleReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminders_service_proto_reminders_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleReminderRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *ScheduleReminderRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *ScheduleReminderRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

type ScheduleReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ScheduleReminderResponse) Reset() {
	*x = ScheduleReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminders_service_proto_reminders_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleReminderResponse) ProtoMessage() {}

func (x *ScheduleReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminders_service_proto_reminders_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleReminderResponse.ProtoReflect.Descriptor instead.
func (*ScheduleReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminders_service_proto_reminders_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleReminderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_reminders_service_proto_reminders_proto protoreflect.FileDescriptor

var file_reminders_service_proto_reminders_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x73, 0x22, 0x7a, 0x0a, 0x17, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x64, 0x75, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x22, 0x32, 0x0a, 0x18, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0x71, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x2f, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reminders_service_proto_reminders_proto_rawDescOnce sync.Once
	file_reminders_service_proto_reminders_proto_rawDescData = file_reminders_service_proto_reminders_proto_rawDesc
)

func file_reminders_service_proto_reminders_proto_rawDescGZIP() []byte {
	file_reminders_service_proto_reminders_proto_rawDescOnce.Do(func() {
		file_reminders_service_proto_reminders_proto_rawDescData = protoimpl.X.CompressGZIP(file_reminders_service_proto_reminders_proto_rawDescData)
	})
	return file_reminders_service_proto_reminders_proto_rawDescData
}

var file_reminders_service_proto_reminders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reminders_service_proto_reminders_proto_goTypes = []interface{}{
	(*ScheduleReminderRequest)(nil),  // 0: reminders.ScheduleReminderRequest
	(*ScheduleReminderResponse)(nil), // 1: reminders.ScheduleReminderResponse
}
var file_reminders_service_proto_reminders_proto_depIdxs = []int32{
	0, // 0: reminders.RemindersService.ScheduleReminder:input_type -> reminders.ScheduleReminderRequest
	1, // 1: reminders.RemindersService.ScheduleReminder:output_type -> reminders.ScheduleReminderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reminders_service_proto_reminders_proto_init() }
func file_reminders_service_proto_reminders_proto_init() {
	if File_reminders_service_proto_reminders_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reminders_service_proto_reminders_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminders_service_proto_reminders_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reminders_service_proto_reminders_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reminders_service_proto_reminders_proto_goTypes,
		DependencyIndexes: file_reminders_service_proto_reminders_proto_depIdxs,
		MessageInfos:      file_reminders_service_proto_reminders_proto_msgTypes,
	}.Build()
	File_reminders_service_proto_reminders_proto = out.File
	file_reminders_service_proto_reminders_proto_rawDesc = nil
	file_reminders_service_proto_reminders_proto_goTypes = nil
	file_reminders_service_proto_reminders_proto_depIdxs = nil
}
