# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_DB_URL: ${{ secrets.USER_DB_URL }}
      USER_DB_USER: ${{ secrets.USER_DB_USER }}
      USER_DB_PASSWORD: ${{ secrets.USER_DB_PASSWORD }}
      USER_DB_NAME: ${{ secrets.USER_DB_NAME }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build Docker images
      run: |
        make build

    - name: Start services
      run: |
        make up

    - name: Apply migrations
      run: |
        make migrate-all

    - name: Run tests
      run: |
        make test

    - name: Stop services
      run: |
        make down
