# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      INVOICE_DB_USER: ${{ secrets.INVOICE_DB_USER }}
      INVOICE_DB_PASSWORD: ${{ secrets.INVOICE_DB_PASSWORD }}
      INVOICE_DB_NAME: ${{ secrets.INVOICE_DB_NAME }}
      INVOICE_DB_PORT: ${{ secrets.INVOICE_DB_PORT }}
      INVOICE_DB_HOST: ${{ secrets.INVOICE_DB_HOST }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build Docker images
      run: |
        make build

    - name: Start services
      run: |
        make up

    - name: Apply migrations
      run: |
        make migrate

    - name: Run tests
      run: |
        make test

    - name: Stop services
      run: |
        make down
